"""
===============================================================================
WASA VERDE Simulation Engine

solar.py

Solar radiation model.

Version 0.1:
    Uses the outdoor solar radiation generated by WeatherModel and computes
    greenhouse transmission and solar heat gain.

Future versions:
    - Solar position
    - Latitude / Longitude
    - Day of year
    - Cloud cover
    - PV electricity production
    - Transparent photovoltaic modules

Author:
    Elham Kashani
Company:
    Aqua Solar Aria B.V.
===============================================================================
"""


from .configuration import GreenhouseConfiguration
from .states import (
    WeatherState,
    SolarState,
)


# =============================================================================
# Solar State
# =============================================================================



# =============================================================================
# Solar Model
# =============================================================================

class SolarModel:
    """
    Computes solar transmission into the greenhouse.
    """

    def __init__(
        self,
        greenhouse: GreenhouseConfiguration,
        transmission: float = 0.80,
        absorptivity: float = 0.85,
    ):
        """
        Parameters
        ----------
        transmission
            Fraction of solar radiation transmitted through the greenhouse
            cover.

        absorptivity
            Fraction of transmitted radiation absorbed inside the greenhouse.
        """

        self.greenhouse = greenhouse

        self.transmission = transmission

        self.absorptivity = absorptivity

    # -------------------------------------------------------------------------

    def transmitted_radiation(
        self,
        radiation: float,
    ) -> float:
        """
        Radiation passing through the greenhouse cover.
        """

        return radiation * self.transmission

    # -------------------------------------------------------------------------

    def solar_heat_gain(
        self,
        transmitted_radiation: float,
    ) -> float:
        """
        Total absorbed solar power.
        """

        return (
            transmitted_radiation
            * self.absorptivity
            * self.greenhouse.floor_area
        )

    # -------------------------------------------------------------------------

    def state(
        self,
        weather: WeatherState,
    ) -> SolarState:
        """
        Compute complete solar state.
        """

        transmitted = self.transmitted_radiation(
            weather.solar_radiation
        )

        absorbed = self.solar_heat_gain(
            transmitted
        )

        return SolarState(

            solar_radiation=weather.solar_radiation,

            transmitted_radiation=transmitted,

            solar_heat_gain=absorbed,
        )


# =============================================================================
# End of File
# =============================================================================
